### ISSUE TITLE
4 variables without unit

### ISSUE THREAD

**Issue by laurinks** [IAMconsortium/common-definitions#134]
The variables [Gender Inequality Index](https://github.com/IAMconsortium/common-definitions/blob/258c943fdbc16f362865367dba68daba50bcac93/definitions/variable/sdg-indicators/sdg.yaml#L152), [Political institutions|Equality before law and individual liberty](https://github.com/IAMconsortium/common-definitions/blob/258c943fdbc16f362865367dba68daba50bcac93/definitions/variable/sdg-indicators/sdg.yaml#L436), [Ocean|Carbonate Saturation|Aragonite and Ocean|Carbonate Saturation|Calcite ](https://github.com/IAMconsortium/common-definitions/blob/258c943fdbc16f362865367dba68daba50bcac93/definitions/variable/sdg-indicators/sdg.yaml#L337) are missing a unit. 

Thank you.

**Comment by danielhuppmann** [comment]
These are unitless variables, see this discussion https://github.com/IAMconsortium/common-definitions/pull/73#issuecomment-2012002837

**Comment by laurinks** [comment]
Happy New Year, @danielhuppmann ! 

I would like to re-open this issue. Would it be possible to explicitly add "unitless", "-" or any other word/symbol to these (and any other) variables that are unitless?

This would make it clear in the variable template that these variables are unitless (instead of a unit being forgotten by mistake), and thereby also be helpful for our internal workflows when preparing submissions to the IIASA database. Thank you!

**Comment by danielhuppmann** [comment]
Frankly, I do not see a good reason for changing the current approach. And the downside of a change would be a change in one or several of the nomenclature, pyam, iam-units, ixmp4, …packages to handle this as a special case.

For adding new variable definitions or working with the yaml files, this will be done by a small set of expert users.

For users working with the xslx template version, I don’t see why a character or a word would be more intuitive than an empty unit column entry.

For reporting and custom analysis scripts by modeling teams, I also don’t see why a bespoke convention would be better than a **None** (yaml/nomenclature) or an empty string (pyam).

**Comment by orichters** [comment]
Well, the actual old approach (in the AR6 database) was to use "dimensionless", for example for `AR6 climate diagnostics|Exceedance Probability 1.5C|MAGICCv7.5.3`. So not allocating any unit seems to be the new approach to me ;). And I think these 5 variables are just numbers, so the unit could be simply set to `1`.

I agree with Laurin that an empty cell looks more like an error (and it took us a bit of time to get our submission scripts right because they treated a lacking unit as an error, because it happened several time that the unit just *was* forgotten).
