### ISSUE TITLE
Ambiguities about R10 in actual use, and South Korea in "China+ (R10)" region?

### ISSUE THREAD

**Issue by korsbakken** [IAMconsortium/common-definitions#160]
In models that I encounter in projects, there appears to be a lot of variations in how the different models map to the R10 regions. In particular east and southeast Asian countries. Many models place both Taiwan and North Korea in the "Rest of Asia" region, while some place them in "China+" ("Centrally-planned Asia").

The confusion here seems to stem from at least two places:
* The AR6 WGIII model registration template (attached here: [IPCC_AR6_model_registration_2019-10-23.xlsx](https://github.com/user-attachments/files/17267347/IPCC_AR6_model_registration_2019-10-23.xlsx)) contains errors in the definition of R10. Most significantly, centrally-planned Asian countries other than China are listed twice, under both R10CHINA+ and R10REST_ASIA, while South Korea and all the non-communist or non-former-communist southeast Asian countries aren't listed anywhere at all. Nor are any north African countries.
* The original source given in common-definitions, the LIIMITS project, doesn't have a clear definition of most regions, and notes that there is large variation between the participating models, including for both Asia and North Africa/Middle East. [https://tntcat.iiasa.ac.at/LIMITSDB/static/download/LIMITS_10+1_regions.pdf](https://tntcat.iiasa.ac.at/LIMITSDB/static/download/LIMITS_10+1_regions.pdf)

Given this, I have two questions:
1. Should common-definitions include R10 regions at all? In some way it is useful to try to settle a clear definition. But on the other hand, most models are not going to change the definition they have used, and certainly not in the existing literature. Which means that someone who takes the region definitions from common-definitions, thinking they are authoritative and not knowing about the ambiguities, might end up confused and wasting time trying to figure out why they can't get the numbers in the scenario databases to add up.
2. If common-definitions does keep the R10 regions, does it make sense to place South Korea in China+? It's neither centrally planned nor does it fit well with the other countries in that region in other respects. To my mind, the only logical place for it would be in Pacific OECD along with Japan, but I see many models put it in "Rest of Asia" (maybe because the WGIII template and LIMITS don't list it under Pacific OECD).

Here's the current placement of South Korea under China+ in common-definitions:

https://github.com/IAMconsortium/common-definitions/blob/1869816c14a1d7808ce8567f6d55abdb180032d8/definitions/region/common.yaml#L192

**Comment by danielhuppmann** [comment]
Yes, previous region-definitions spreadsheets and pdf's were partly inconsistent. That's why I spent some effort on a clean-up and this repository should now be treated as "source of truth" for definitions of aggregate-regions R5/R9/R10, etc.

Yes, most models cannot directly represent the aggregate-regions because of inconsistent native regions. But the common-definitions repository at least has (should have) the full country-mapping, and it would be quite straightforward to develop methods to get the countries that are actually included in a common-region for a specific model, see https://github.com/IAMconsortium/nomenclature/issues/403.

The R10-regions are a derivative of the R5-regions, and those have the OECD-countries with their membership status as of 1990. Hence, South Korea is not included in the OECD from the R5/R10-perspective.

I agree that the description of "China+ (R10)" could be changed to so as to remove the phrase "centrally planned". I'd be very hesitant to make any major changes to the default-country-definitions of the aggregate regions because this would cause even more confusion.

**Comment by korsbakken** [comment]
OK, thanks for looking into it and clarifying the description. I think the real issue here is that how the models in question actually have used China+ and other R10 regions in existing modelling work varies widely, which means that what they call R10 China+ (and several other regions) can't be compared across models or with what you get from doing region aggregawtion with the current `common-definitions` mappings. But that's not something that can be fixed by making changes in `common-definitions` anyway.

**Comment by danielhuppmann** [comment]
Right, each model has some native regional resolution and they don't match - no definition of common regions for comparison can get around that.

I can only repeat that https://github.com/IAMconsortium/nomenclature/issues/403 has a piece of code that can help you get clarity on which countries are *actually represented* in each common region for a particular model.
